name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - voila
  - xarray
  - cartopy
  - proplot
  - netCDF4
  - wrf
  - pandas
